# Generated by Django 5.2.7 on 2025-10-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pytania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiom', models.TextField()),
                ('answerA', models.TextField()),
                ('answerB', models.TextField()),
                ('answerC', models.TextField()),
                ('answerD', models.TextField()),
                ('answerCorrect', models.CharField(max_length=1)),
                ('img', models.TextField()),
            ],
        ),
    ]
