# Generated by Django 5.2.7 on 2025-10-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pytania',
            new_name='questions',
        ),
    ]
