# Generated by Django 5.2.7 on 2025-10-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_pytania_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='questiom',
            new_name='question',
        ),
    ]
