# Generated by Django 5.2.7 on 2025-10-15 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_rename_questiom_questions_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(choices=[('INF 02', 'INF 02'), ('INF 03', 'INF 03'), ('INF 04', 'INF 04')], default='INF 03', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='scores_score_range')],
            },
        ),
    ]
