# Generated by Django 5.2.7 on 2025-10-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_questiontypes_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='hello.questiontypes'),
        ),
        migrations.AddField(
            model_name='scores',
            name='examType',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='hello.questiontypes'),
            preserve_default=False,
        ),
    ]
