# Generated by Django 5.2.7 on 2025-10-27 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_questions_question_type_scores_examtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='amountOfQuestions',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.questiontypes'),
        ),
        migrations.AddIndex(
            model_name='questions',
            index=models.Index(fields=['id', 'question_type'], name='hello_quest_id_c6cdca_idx'),
        ),
        migrations.AddIndex(
            model_name='questions',
            index=models.Index(fields=['question_type'], name='hello_quest_questio_0f8d95_idx'),
        ),
        migrations.AddIndex(
            model_name='scores',
            index=models.Index(fields=['examType'], name='hello_score_examTyp_c8f491_idx'),
        ),
    ]
