# Generated by Django 5.2.7 on 2025-10-29 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_scores_amountofquestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='exam_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
