# Generated by Django 5.2.7 on 2025-10-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_scores_exam_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scores',
            name='hello_score_examTyp_c8f491_idx',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='answerA',
            new_name='answer_a',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='answerB',
            new_name='answer_b',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='answerC',
            new_name='answer_c',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='answerCorrect',
            new_name='answer_correct',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='answerD',
            new_name='answer_d',
        ),
        migrations.RenameField(
            model_name='questiontypes',
            old_name='questionType',
            new_name='question_type',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='amountOfQuestions',
            new_name='amount_of_questions',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='examType',
            new_name='exam_type',
        ),
        migrations.AddIndex(
            model_name='scores',
            index=models.Index(fields=['exam_type'], name='hello_score_exam_ty_1d65cb_idx'),
        ),
    ]
